"""Add LiveTrade model

Revision ID: 2dc9e43d09ce
Revises: 5549b2cd6d1f
Create Date: 2026-03-04 14:48:08.924902
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '2dc9e43d09ce'
down_revision: Union[str, None] = '5549b2cd6d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('instrument_key', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='live_trade_direction'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'PARTIALLY_FILLED', 'REJECTED', 'CANCELLED', 'CLOSED', name='live_trade_status'), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_trades_broker_order_id'), 'live_trades', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_live_trades_status'), 'live_trades', ['status'], unique=False)
    op.create_index(op.f('ix_live_trades_symbol'), 'live_trades', ['symbol'], unique=False)
    op.drop_table('auto_trade_log')
    op.drop_table('auto_trade_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trade_config',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('qty_per_trade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_open_positions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('watchlist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scan_interval_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sizing_mode', sa.VARCHAR(length=10), server_default=sa.text("'capital'::character varying"), autoincrement=False, nullable=False),
    sa.Column('capital_per_trade', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('10000.0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auto_trade_config_pkey'))
    )
    op.create_table('auto_trade_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('signal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_reward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rsi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auto_trade_log_pkey'))
    )
    op.drop_index(op.f('ix_live_trades_symbol'), table_name='live_trades')
    op.drop_index(op.f('ix_live_trades_status'), table_name='live_trades')
    op.drop_index(op.f('ix_live_trades_broker_order_id'), table_name='live_trades')
    op.drop_table('live_trades')
    # ### end Alembic commands ###
