"""Add volume and spread filters to RiskConfig

Revision ID: 3c46a7986c10
Revises: 5e8ec94d5461
Create Date: 2026-03-04 14:56:10.809707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3c46a7986c10'
down_revision: Union[str, None] = '5e8ec94d5461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_config', sa.Column('min_daily_volume', sa.Integer(), nullable=True))
    op.add_column('risk_config', sa.Column('max_spread_pct', sa.Numeric(precision=6, scale=4), nullable=True))
    op.drop_column('risk_config', 'max_position_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_config', sa.Column('max_position_pct', sa.NUMERIC(precision=6, scale=4), server_default=sa.text('0.20'), autoincrement=False, nullable=True))
    op.drop_column('risk_config', 'max_spread_pct')
    op.drop_column('risk_config', 'min_daily_volume')
    # ### end Alembic commands ###
