"""Add paper trading models

Revision ID: 5549b2cd6d1f
Revises: aeecb8c9bbea
Create Date: 2026-03-03 07:46:53.215783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '5549b2cd6d1f'
down_revision: Union[str, None] = 'aeecb8c9bbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('instrument_key', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='paper_trade_direction'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='paper_trade_status'), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_status'), 'paper_trades', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    op.add_column('risk_config', sa.Column('paper_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_config', 'paper_balance')
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_status'), table_name='paper_trades')
    op.drop_table('paper_trades')
    # ### end Alembic commands ###
