"""Add max_slippage_pct to AutoTradeConfig

Revision ID: 5e8ec94d5461
Revises: 2dc9e43d09ce
Create Date: 2026-03-04 14:49:49.299524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '5e8ec94d5461'
down_revision: Union[str, None] = '2dc9e43d09ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
