"""add_instrument_key_to_symbols

Revision ID: aeecb8c9bbea
Revises: 006
Create Date: 2026-03-02 07:41:15.168801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'aeecb8c9bbea'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_event'), table_name='audit_log')
    op.create_index('idx_audit_event', 'audit_log', ['event_type', 'timestamp'], unique=False)
    op.drop_index(op.f('idx_audit_timestamp'), table_name='audit_log')
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.drop_index(op.f('candles_time_idx'), table_name='candles')
    op.drop_index(op.f('idx_candles_symbol_time'), table_name='candles')
    op.create_index('idx_candles_symbol_time', 'candles', ['symbol_id', 'time'], unique=False)
    op.drop_index(op.f('idx_risk_config_singleton'), table_name='risk_config')
    op.drop_index(op.f('idx_signals_status'), table_name='signals')
    op.create_index('idx_signals_status', 'signals', ['risk_status', 'timestamp'], unique=False)
    op.drop_index(op.f('idx_signals_symbol'), table_name='signals')
    op.create_index('idx_signals_symbol', 'signals', ['symbol_id', 'timestamp'], unique=False)
    op.drop_index(op.f('idx_signals_timestamp'), table_name='signals')
    op.create_index('idx_signals_timestamp', 'signals', ['timestamp'], unique=False)
    op.add_column('symbols', sa.Column('instrument_key', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_trades_date'), table_name='trades')
    op.create_index('idx_trades_date', 'trades', ['trade_date'], unique=False)
    op.drop_index(op.f('idx_trades_symbol'), table_name='trades')
    op.create_index('idx_trades_symbol', 'trades', ['symbol_id', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.create_index(op.f('idx_trades_symbol'), 'trades', ['symbol_id', sa.literal_column('trade_date DESC')], unique=False)
    op.drop_index('idx_trades_date', table_name='trades')
    op.create_index(op.f('idx_trades_date'), 'trades', [sa.literal_column('trade_date DESC')], unique=False)
    op.drop_column('symbols', 'instrument_key')
    op.drop_index('idx_signals_timestamp', table_name='signals')
    op.create_index(op.f('idx_signals_timestamp'), 'signals', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_signals_symbol', table_name='signals')
    op.create_index(op.f('idx_signals_symbol'), 'signals', ['symbol_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_signals_status', table_name='signals')
    op.create_index(op.f('idx_signals_status'), 'signals', ['risk_status', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_risk_config_singleton'), 'risk_config', [sa.literal_column('(true)')], unique=True)
    op.drop_index('idx_candles_symbol_time', table_name='candles')
    op.create_index(op.f('idx_candles_symbol_time'), 'candles', ['symbol_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('candles_time_idx'), 'candles', [sa.literal_column('time DESC')], unique=False)
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.create_index(op.f('idx_audit_timestamp'), 'audit_log', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_audit_event', table_name='audit_log')
    op.create_index(op.f('idx_audit_event'), 'audit_log', ['event_type', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
