"""
QuantDSS Metrics Collection — Prometheus Instrumentation
"""
from prometheus_client import Counter, Gauge, Histogram, REGISTRY

# ── Business Metrics ─────────────────────────────────────────────────────────

SIGNALS_GENERATED = Counter(
    "quantdss_signals_generated_total",
    "Total number of signals generated by the system",
    ["strategy"]
)

SIGNALS_REJECTED = Counter(
    "quantdss_signals_rejected_total",
    "Total number of signals rejected by the Risk Engine",
    ["reason"]
)

TRADES_EXECUTED = Counter(
    "quantdss_trades_executed_total",
    "Total number of trades executed by AutoTrader",
    ["symbol", "strategy", "type"]
)

TRADE_FAILURES = Counter(
    "quantdss_trade_failures_total",
    "Total number of trade execution failures",
    ["symbol", "reason"]
)

# ── Infrastructure Metrics ───────────────────────────────────────────────────

REDIS_STREAM_LAG = Gauge(
    "quantdss_redis_stream_lag",
    "Estimated or actual lag in Redis Stream processing",
    ["stream_name", "consumer_group"]
)

WORKER_UPTIME = Gauge(
    "quantdss_worker_uptime_seconds",
    "Uptime of worker processes in seconds",
    ["worker_name"]
)

BROKER_API_LATENCY = Histogram(
    "quantdss_broker_api_latency_seconds",
    "Latency of Broker API calls",
    ["endpoint", "method"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
)

EXECUTION_LATENCY = Histogram(
    "quantdss_execution_latency_seconds",
    "End-to-end latency from signal to broker execution",
    ["strategy"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
)
